# BNBstoken <BNBistoken.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GAIRK7D3EZ3KNOFUFMOEMY5SAPWZ4AV3WDOHCHMO4ACOQQRZLBFFXGH7"
]

[DOCUMENTATION]
ORG_NAME="BNBistoken"
ORG_URL="https://bnbchain9.github.io/"
ORG_LOGO = "https://bnbchain9.github.io/img/btc.png"
ORG_OFFICIAL_EMAIL="none"
ORG_SUPPORT_EMAIL="none"
ORG_TWITTER="none"
ORG_DESCRIPTION="BNBistoken: Create Value to Meme Coin Space"

[[PRINCIPALS]]
email="none"

[[CURRENCIES]]
code = "BNB"
name = "BNB"
issuer = "GAIRK7D3EZ3KNOFUFMOEMY5SAPWZ4AV3WDOHCHMO4ACOQQRZLBFFXGH7"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of BNB."
image="https://stellarzoom.github.io/img/anubis.png"
conditions="There will only ever be 1 billion BNB tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code = "BTC"
name = "BTC"
issuer = "GAIRK7D3EZ3KNOFUFMOEMY5SAPWZ4AV3WDOHCHMO4ACOQQRZLBFFXGH7"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of BTC."
image="https://bnbchain9.github.io/img/btc.png"
conditions="There will only ever be 1 billion BTC tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000
