# BNB token <BNB is token.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GAIRK7D3EZ3KNOFUFMOEMY5SAPWZ4AV3WDOHCHMO4ACOQQRZLBFFXGH7"
]

[DOCUMENTATION]
ORG_NAME="BNB is token"
ORG_URL="https://bnbchain9.github.io/"
ORG_LOGO = "https://bnbchain9.github.io/img/btc.png"
ORG_OFFICIAL_EMAIL="bnbchain9@proton.me"
ORG_SUPPORT_EMAIL="bnbchain9@proton.me"
ORG_TWITTER="none"
ORG_DESCRIPTION="BNB is token: Create Value to Meme Interstellar"

[[PRINCIPALS]]
email="bnbchain9@proton.me"

[[CURRENCIES]]
code = "BNB"
name = "BNB"
issuer = "GAIRK7D3EZ3KNOFUFMOEMY5SAPWZ4AV3WDOHCHMO4ACOQQRZLBFFXGH7"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of BNB."
image="https://bnbchain9.github.io/img/BNB.png"
conditions="There will only ever be 1 billion BNB tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code = "BTC"
name = "BTC"
issuer = "GAIRK7D3EZ3KNOFUFMOEMY5SAPWZ4AV3WDOHCHMO4ACOQQRZLBFFXGH7"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of BTC."
image="https://bnbchain9.github.io/img/BTC.png"
conditions="There will only ever be 1 billion BTC tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code = "AI"
name = "AI"
issuer = "GAIRK7D3EZ3KNOFUFMOEMY5SAPWZ4AV3WDOHCHMO4ACOQQRZLBFFXGH7"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of AI."
image="https://bnbchain9.github.io/img/AI.png"
conditions="There will only ever be 1 billion AI tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code = "USDC"
name = "USDC"
issuer = "GAIRK7D3EZ3KNOFUFMOEMY5SAPWZ4AV3WDOHCHMO4ACOQQRZLBFFXGH7"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of USDC."
image="https://bnbchain9.github.io/img/USDC.png"
conditions="There will only ever be 1 billion USDC tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code = "XRP"
name = "XRP"
issuer = "GAIRK7D3EZ3KNOFUFMOEMY5SAPWZ4AV3WDOHCHMO4ACOQQRZLBFFXGH7"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of XRP."
image="https://bnbchain9.github.io/img/XRP.png"
conditions="There will only ever be 1 billion XRP tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000


